/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_netty_resolver_dns_windows_NativeWrapper */

#ifndef _Included_io_netty_resolver_dns_windows_NativeWrapper
#define _Included_io_netty_resolver_dns_windows_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_netty_resolver_dns_windows_NativeWrapper
 * Method:    resolvers
 * Signature: ()[Lio/netty/resolver/dns/windows/DnsResolver;
 */
JNIEXPORT jobjectArray JNICALL Java_io_netty_resolver_dns_windows_NativeWrapper_resolvers
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
